SHELL:=/bin/bash

all: main.x

%.x: %.o factorial.o 
	g++ $^ -o $@ -l 

test_factorial.x: factorial_test.o factorial.o
	g++ $^ -o $@ -l Catch2Main -l Catch2

test: test_factorial.x
	./test_factorial.x

%.o: %.cpp
	g++ -c $<

clean:
	rm -f *.o *.x