SHELL:=/bin/bash


all: main.x

%.o: %.cpp
	g++ -c $<

%.x: %.o factorial.o 
	g++ $^ -o $@ 

test_factorial.x: factorial_test.o factorial.o
	g++ $^ -o $@ -l Catch2Main -l Catch2

test: test_factorial.x
	./test_factorial.x

clean:
	rm -f *.o *.x *.out